steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/verifactu-repo/verifactu-app:$BUILD_ID'
      - -t
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/verifactu-repo/verifactu-app:$SHORT_SHA'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/verifactu-repo/verifactu-app:$BUILD_ID'
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/verifactu-repo/verifactu-app:$SHORT_SHA'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - verifactu-app
      - --image=europe-west1-docker.pkg.dev/$PROJECT_ID/verifactu-repo/verifactu-app:$BUILD_ID
      - --region=europe-west1
      - --allow-unauthenticated
      - --service-account=cr-runtime@$PROJECT_ID.iam.gserviceaccount.com
timeout: "1200s"
