name: Deploy to Cloud Run (dev) – lite

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGION: ${{ vars.CLOUD_RUN_REGION }}              # ej. europe-west1
      SERVICE: ${{ vars.CLOUD_RUN_SERVICE }}            # ej. verifactu-app-dev
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}         # verifactu-business
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate to Google Cloud via WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WIF_POOL }}/providers/${{ secrets.WIF_PROVIDER }}
          service_account: isaak-agent@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy from source (Buildpacks) using isaak-agent as build SA
        shell: bash
        run: |
          gcloud run deploy "${SERVICE}" \
            --region="${REGION}" \
            --source="." \
            --build-service-account="projects/${PROJECT_ID}/serviceAccounts/isaak-agent@${PROJECT_ID}.iam.gserviceaccount.com" \
            --service-account="projects/${PROJECT_ID}/serviceAccounts/run-runtime@${PROJECT_ID}.iam.gserviceaccount.com" \
            --allow-unauthenticated

      - name: Show service URL
        shell: bash
        run: |
          gcloud run services describe "${SERVICE}" --region="${REGION}" --format='value(status.url)'
